 export const translations = {
    en: {
      subtitle: "Modern, customizable and beautiful gradient avatars for React components",
      npmButton: "NPM",
      customizable: "Customizable",
      customizableDesc: "Size, shape and color settings",
      lightweight: "Lightweight",
      lightweightDesc: "Minimalist and performant",
      easy: "Easy",
      easyDesc: "Simple integration",
      demo: "Demo",
      installation: "Installation",
      examples: "Examples",
      gallery: "Gallery",
      interactiveDemo: "Interactive Demo",
      name: "Name",
      enterName: "Enter a name",
      size: "Size",
      shape: "Shape",
      circle: "Circle",
      square: "Square",
      color: "Color",
      terminal: "Terminal",
      copy: "Copy",
      copied: "Copied",
      basicUsage: "Basic Usage",
      props: "Properties (Props)",
      propTitle: "Name for avatar (required)",
      propSize: "Avatar size in pixels (default: 40)",
      propShape: "\"circle\" or \"square\" (default: \"circle\")",
      propColor: "Custom color code (default: automatic gradient)",
      usageExamples: "Usage Examples",
      default: "Default",
      squareShape: "Square Shape",
      customColor: "Custom Color",
      avatarGroup: "Avatar Group",
      advancedUsage: "Advanced Usage",
      userCardExample: "User Card Example",
      developer: "Developer",
      commentExample: "Comment Example",
      yesterday: "Yesterday",
      commentText: "This library is great, we use it in our project!",
      avatarGallery: "Avatar Gallery",
      colorPalette: "Color Palette",
      followText: "Follow me and discover my new projects!",
      copyright: "Design and development © 2025 Mustafa Karaçuha"
    },
    tr: {
      subtitle: "Modern, özelleştirilebilir ve güzel gradient avatarlar için React bileşeni",
      npmButton: "NPM",
      customizable: "Özelleştirilebilir",
      customizableDesc: "Boyut, şekil ve renk ayarları",
      lightweight: "Hafif",
      lightweightDesc: "Minimalist ve performanslı",
      easy: "Kolay",
      easyDesc: "Basit entegrasyon",
      demo: "Demo",
      installation: "Kurulum",
      examples: "Örnekler",
      gallery: "Galeri",
      interactiveDemo: "İnteraktif Demo",
      name: "İsim",
      enterName: "Bir isim girin",
      size: "Boyut",
      shape: "Şekil",
      circle: "Daire",
      square: "Kare",
      color: "Renk",
      terminal: "Terminal",
      copy: "Kopyala",
      copied: "Kopyalandı",
      basicUsage: "Temel Kullanım",
      props: "Özellikler (Props)",
      propTitle: "Avatar için isim (gerekli)",
      propSize: "Avatar boyutu pikseller cinsinden (varsayılan: 40)",
      propShape: "\"circle\" veya \"square\" (varsayılan: \"circle\")",
      propColor: "Özel renk kodu (varsayılan: otomatik gradient)",
      usageExamples: "Kullanım Örnekleri",
      default: "Varsayılan",
      squareShape: "Kare Şekli",
      customColor: "Özel Renk",
      avatarGroup: "Avatar Grubu",
      advancedUsage: "Gelişmiş Kullanım",
      userCardExample: "Kullanıcı Kartı Örneği",
      developer: "Geliştirici",
      commentExample: "Yorum Örneği",
      yesterday: "Dün",
      commentText: "Bu kütüphane harika, projemizde kullanıyoruz!",
      avatarGallery: "Avatar Galerisi",
      colorPalette: "Renk Paleti",
      followText: "Takip edin ve yeni projelerimi keşfedin!",
      copyright: "Tasarım ve geliştirme © 2025 Mustafa Karaçuha"
    }
  };
